DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS bottles;
DROP TABLE IF EXISTS logs;

CREATE TABLE IF NOT EXISTS users(
  uid VARCHAR(255) NOT NULL,
  PRIMARY KEY (uid)
);

CREATE TABLE IF NOT EXISTS bottles(
  bid INT NOT NULL,
  uid VARCHAR(255) NOT NULL,
  max_val INT NOT NULL, 
  PRIMARY KEY (bid, uid),
  FOREIGN KEY (uid)
    REFERENCES users (uid)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS logs(
  uid VARCHAR(255) NOT NULL,
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  val INT(11) NOT NULL
);